{% set org = "tdegeus" %}
{% set name = "GMatTensor" %}
{% set version = "0.7.1" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 2fb4b0b92582abb54b34566f24b2f8b016cb18fe178b18feec91bad19d4a18aa

build:
  number: 0
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - setuptools_scm
    - pyxtensor
  run:
    - python

test:
  imports:
    - {{ name }}
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tensor definitions supporting several GMat models.
  description: Tensor definitions supporting several GMat models.
  doc_url: https://{{ org }}.github.io/{{ name }}
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
