{% set name = "python-gmattensor" %}
{% set version = "0.1.2" %}
{% set sha256 = "9733e70bc59ca90bcb8c28cbc3f08bff24020313a5105d48460da434005733dc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GMatTensor/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - pyxtensor
  run:
    - python

test:
  imports:
    - GMatTensor

about:
  home: https://github.com/tdegeus/GMatTensor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tensor definitions supporting several GMat models.
  description: Tensor definitions supporting several GMat models.
  doc_url: https://github.com/tdegeus/GMatTensor
  dev_url: https://github.com/tdegeus/GMatTensor

extra:
  recipe-maintainers:
    - tdegeus
